### ISSUE TITLE
Broken INA226 link

### ISSUE THREAD

**Issue by sipvoip** [mamin27/ecomet_i2c_raspberry_tools#5]
https://github.com/mamin27/ecomet_i2c_raspberry_tools/blob/master/ecomet_i2c_sensors/ina260/ina260_python.IIC.md

Trying to see how to use this lib on a raspberry pi and ina226, but the link on the page is dead.

**Comment by mamin27** [comment]
Hi, link is dead because I had not time to do documentation. Firstly I waited for fixing code issue then I planned to prepare code documentation. Currently I am busy with hardware design (you will see at my twitter) so give me 2 weeks to fulfill it. I am just alone for software and hardware. That's reason why. But you could support me with the star to support my engineering energy.

**Comment by mamin27** [comment]
Try to look now. In case of any not clear doc details let me know. Link is now https://github.com/mamin27/ecomet_i2c_raspberry_tools/blob/master/ecomet_i2c_sensors/ina260/ina260_python_IIC.md
